### ISSUE TITLE
TF IS THIS 😭??  8 year old code??

### ISSUE THREAD

**Issue by unknoxx** [KURO-CODE/DoxTracker#11]

**Comment by M33KS1N1ST3R** [comment]
> 

Don't waste your time on this 🤣 literally doesn't work 😂

**Comment by Kahmikazi** [comment]
I have fixed the code. If you would like the working DoxTracker.py Please, let me know.

**Comment by Gihubuser12** [comment]
> I have fixed the code. If you would like the working DoxTracker.py Please, let me know.

hey could you give me the working version of doxtracer.py message me on discord breadman#6862

**Comment by Kahmikazi** [comment]
> > I have fixed the code. If you would like the working DoxTracker.py Please, let me know.
> 
> 
> 
> hey could you give me the working version of doxtracer.py message me on discord breadman#6862


I have added you on there

**Comment by Gihubuser12** [comment]
> > > I have fixed the code. If you would like the working DoxTracker.py Please, let me know.
> > 
> > 
> > hey could you give me the working version of doxtracer.py message me on discord breadman#6862
> 
> I have added you on there

Could  you give me the working version of doxtracer.py on discord please, I only want this to learn about cyber safety and i am planning on making a counter to this.

**Comment by Gihubuser12** [comment]
> > > I have fixed the code. If you would like the working DoxTracker.py Please, let me know.
> > 
> > 
> > hey could you give me the working version of doxtracer.py message me on discord breadman#6862
> 
> I have added you on there

I am sorry for being so impatient but it has been 17 hours and I were wondering if you forgot, If you are still at the confrence sorry but when you get home please send me DoxTracer.py on discord

**Comment by Gihubuser12** [comment]
> I have fixed the code. If you would like the working DoxTracker.py Please, let me know.

I am so sorry for being really impatient but why is your confrence taking 40 hours?

**Comment by Gihubuser12** [comment]
> > > I have fixed the code. If you would like the working DoxTracker.py Please, let me know.
> > 
> > 
> > hey could you give me the working version of doxtracer.py message me on discord breadman#6862
> 
> I have added you on there

Sorry for disturbing you so much but the link you sent me does not work, Could you please make a media fire one?

**Comment by Flamesour** [comment]
please also add me

**Comment by shadow05github** [comment]
> I have fixed the code. If you would like the working DoxTracker.py Please, let me know.
Add me on discord please , my username is Shadow05#7565

**Comment by OTW-cyber** [comment]
> I have fixed the code. If you would like the working DoxTracker.py Please, let me know.

me too? OTW#0001 im looking for a really good dox tool

**Comment by young-tea** [comment]
> I have fixed the code. If you would like the working DoxTracker.py Please, let me know.

Oh, can you send it to mee too pls? y0ung_tea
